In [ ]:
import sys
import numpy as np
import time


In [ ]:
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [ ]:
#Mutable Data Type Example(List)
my_list = [1, 2, 3]
print("Original List:", my_list)

#Modifying the list (Changing contents)
my_list . append(4)
print("Modified List:", my_list)

#Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
#my_tuple. append(4)
print("Original Tuple:", my_tuple)

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [ ]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi ))
print("data type of variable temperature = ", type(temperature))


data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


In [ ]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ", type(name))
print("data type of the variable greeting = ", type(greeting))
print("data type of the variable address = ", type(address))

#slice only one elements
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])

#slice a range of elements
print("The second letters to the fourth of the name is:", name[1:4])
print("The first two  letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])




data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letters to the fourth of the name is: lic
The first two  letters of the name are: Al
Substring starting from the third letter is: ice


In [ ]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [ ]:
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
#colors[0] = 'purple'
colors # will generate an error as tuple is immutable.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


('red', 'green', 'yellow', 'blue')

In [ ]:
person = {'name':'John','age':30,'city':'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {
person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [ ]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [ ]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [ ]:
num = 10
if num > 0:
  print("Positive")
elif num == 0:
  print("Zero")
else:
  print("Non-positive")

Positive


In [ ]:
x = 5
y = 10
if x > 0 and y < 20:
  print("Both conditions are true")
if x > 0 or y > 20:
  print("At least one condition is true")
if not x == 0:
  print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


In [ ]:
# Define two boolean variables
a = True
b = False
# Using the ’and’ operator
if a and b:
  print("Both a and b are True")
else:
  print("Either a or b is False") # This will be printed
# Using the ’or’ operator
if a or b:
  print("At least one of a or b is True") # This will be printed
else:
  print("Both a and b are False")
# Using the ’not’ operator
if not a:
  print("a is False") # This will not be printed
else:
  print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


In [ ]:
# for loop:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

# While loop:
count = 0
while count < 5:
    print("Count is:", count)
    count += 1

# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit == "apple":
        break

# Continue
print("loop 2")
for fruit in fruits:
    if fruit == "apple":
        continue
    else:
        print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


In [ ]:
def add_binary(a, b):
    '''
    Returns the sum of two decimal numbers in binary digits.

    Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer

    Returns:
    binary_sum (str): Binary string of the sum of a and b
    '''
    binary_sum = bin(a + b)[2:]
    return binary_sum

# Call the function and print the result
print(add_binary(1, 2))

11


In [ ]:
# Print Hello, World!
print("Hello, World!")  # Output: Hello, World!

# Length of a string
length = len("Hello")
print("Length of 'Hello':", length)  # Output: 5

# Data type of a value
data_type = type(42)
print("Data type of 42:", data_type)  # Output: <class 'int'>

# Sum of a list
total = sum([1, 2, 3])
print("Sum of [1, 2, 3]:", total)  # Output: 6

Hello, World!
Length of 'Hello': 5
Data type of 42: <class 'int'>
Sum of [1, 2, 3]: 6


In [ ]:
# str.upper(): Converts all characters in a string to uppercase
message = "hello".upper()
print("Uppercase message:", message)  # Output: HELLO

# list.append(): Adds an element to the end of a list
fruits = ["apple", "banana"]
fruits.append("cherry")
print("Updated fruits list:", fruits)  # Output: ['apple', 'banana', 'cherry']

# dict.get(): Returns the value associated with a key in a dictionary
info = {"name": "Alice", "age": 25}
age = info.get("age")
print("Age from dictionary:", age)  # Output: 25

Uppercase message: HELLO
Updated fruits list: ['apple', 'banana', 'cherry']
Age from dictionary: 25


In [ ]:
def temperature_converter():
  '''
  Converts temperature between Celsius and Fahrenheit.
  This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
  Fahrenheit to Celsius)
  and then asks for the temperature value. It calculates and returns the converted temperature.
  Returns:
  float: The converted temperature value.
  '''
  print("Choose conversion type:")
  print("1. Celsius to Fahrenheit")
  print("2. Fahrenheit to Celsius")
  # Get conversion choice from user
  choice = input("Enter 1 or 2: ")
  if choice == "1":
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}C is equal to {fahrenheit}F")
    return fahrenheit
  elif choice == "2":
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print(f"{fahrenheit}F is equal to {celsius}C")
    return celsius
  else:
    print("Invalid choice. Please enter 1 or 2.")
    return None

# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 2
Enter temperature in Fahrenheit: 98
98.0F is equal to 36.666666666666664C


36.666666666666664

In [ ]:
x = 10 # Global Variable.
def print_global():
  print(x) # Accessing global variable
print_global() # Output: 10

10


In [ ]:
def print_local():
    y = 5  # Local variable
    print("Inside function:", y)

print_local()  # Output: 5



Inside function: 5


In [ ]:
x = 10 # Global variable
def modify_global():
  global x # Declaring x as global
x = 20 # Modifying global x
modify_global()
print(x) # Output: 20

20


TO-DO-TASK
EXERCISE ON FUNCTION
TASK-1

In [ ]:
def convert_units(value, conversion_type):
    """
    Performs conversion between different units.

    Parameters:
    value (float): The numeric value to convert.
    conversion_type (int): The choice representing the specific conversion type.

    Returns:
    float: The converted value.

    Raises:
    ValueError: If conversion_type is invalid.
    """
    # Conversion factors
    METERS_TO_FEET = 3.28084
    KG_TO_LBS = 2.20462
    LITERS_TO_GALLONS = 0.264172

    if conversion_type == 1:
        return value * METERS_TO_FEET
    elif conversion_type == 2:
        return value / METERS_TO_FEET
    elif conversion_type == 3:
        return value * KG_TO_LBS
    elif conversion_type == 4:
        return value / KG_TO_LBS
    elif conversion_type == 5:
        return value * LITERS_TO_GALLONS
    elif conversion_type == 6:
        return value / LITERS_TO_GALLONS
    else:
        raise ValueError("Invalid conversion choice.")


def main_converter():
    while True:
        print("\nUnit Conversion Program")
        print("1. Meters to Feet")
        print("2. Feet to Meters")
        print("3. Kilograms to Pounds")
        print("4. Pounds to Kilograms")
        print("5. Liters to Gallons")
        print("6. Gallons to Liters")
        print("0. Exit")

        try:
            choice = int(input("Select conversion (0-6): "))
            if choice == 0:
                print("Exiting program.")
                break
            value = float(input("Enter the value to convert: "))
            converted_value = convert_units(value, choice)
            print(f"Converted value: {converted_value:.2f}")
        except ValueError as e:
            print(f"Error: {e}. Please enter numeric values and valid choices only.")


if __name__ == "__main__":
    main_converter()


Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
0. Exit
Select conversion (0-6): 1
Enter the value to convert: 11
Converted value: 36.09

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
0. Exit
Select conversion (0-6): 0
Exiting program.


TASK-2

In [ ]:
def get_sum(numbers):
    """Calculates the sum of all numbers in a list."""
    return sum(numbers)

def get_average(numbers):
    """Calculates the arithmetic mean of a list of numbers."""
    return sum(numbers) / len(numbers) if numbers else 0

def get_max(numbers):
    """Finds the maximum value in a list of numbers."""
    return max(numbers)

def get_min(numbers):
    """Finds the minimum value in a list of numbers."""
    return min(numbers)

def main():
    print("Math operations on Lists")
    print("Available operations: sum, average, max, min")
    print("Type 'exit' to quit the program.")

    while True:
        operation = input("\nEnter the operation (sum, average, max, min) or 'exit': ").strip().lower()
        if operation == "exit":
            print("Exiting program.")
            break

        numbers_str = input("Enter a list of numbers separated by spaces: ").strip()
        try:
            numbers = [float(num) for num in numbers_str.split()]
            if not numbers:
                print("The list is empty. Please enter at least one number.")
                continue

            if operation == "sum":
                result = get_sum(numbers)
            elif operation == "average":
                result = get_average(numbers)
            elif operation == "max":
                result = get_max(numbers)
            elif operation == "min":
                result = get_min(numbers)
            else:
                print("Invalid operation. Please choose from sum, average, max, or min.")
                continue

            print(f"Result: {result}")

        except ValueError:
            print("Error: Please enter numeric values only.")

if __name__ == "__main__":
    main()

Math operations on Lists
Available operations: sum, average, max, min
Type 'exit' to quit the program.

Enter the operation (sum, average, max, min) or 'exit': sum
Enter a list of numbers separated by spaces: 2 3
Result: 5.0

Enter the operation (sum, average, max, min) or 'exit': exit
Exiting program.


In [ ]:
# List Manipulation Functions

# Extract every other element
def extract_every_other(lst):
    """Returns every other element starting from the first."""
    return lst[::2]

# Slice a sublist
def get_sublist(lst, start, end):
    """Returns a sublist from start to end ."""
    return lst[start:end + 1]

# Reverse a list using slicing
def reverse_list(lst):
    """Returns the list in reverse order."""
    return lst[::-1]

# Remove first and last elements
def remove_first_last(lst):
    """Returns the list without the first and last elements."""
    return lst[1:-1]

#  Get first n elements
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

# Extract last n elements
def extract_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

# Extract elements in reverse order skipping one
def reverse_skip(lst):
    """Returns every second element starting from the second to last moving backward."""
    return lst[-2::-2]

# Test the functions
test_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print("Original List:", test_list)
print(f"Every Other: {extract_every_other(test_list)}")
print(f"Sublist (2-4): {get_sublist(test_list, 2, 4)}")
print(f"Reverse List: {reverse_list(test_list)}")
print(f"Remove First/Last: {remove_first_last(test_list)}")
print(f"First 3: {get_first_n(test_list, 3)}")
print(f"Last 2: {extract_last_n(test_list, 2)}")
print(f"Reverse Skip: {reverse_skip(test_list)}")

Original List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Every Other: [1, 3, 5, 7, 9]
Sublist (2-4): [3, 4, 5]
Reverse List: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
Remove First/Last: [2, 3, 4, 5, 6, 7, 8, 9]
First 3: [1, 2, 3]
Last 2: [9, 10]
Reverse Skip: [9, 7, 5, 3, 1]


In [ ]:
#  Basic flatten
def flatten(lst):
    return [item for sublist in lst for item in sublist]

# Accessing Elements
def access_nested_element(lst, indices):
    current = lst
    for index in indices:
        current = current[index]
    return current

# Deep Flatten
def deep_flatten(lst):
    flat = []
    for item in lst:
        if isinstance(item, list):
            flat.extend(deep_flatten(item))
        else:
            flat.append(item)
    return flat

#  Sum (Use deep_flatten for any depth)
def sum_nested(lst):
    return sum(deep_flatten(lst))

# Remove element
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

#  Max
def find_max(lst):
    return max(deep_flatten(lst))

#  Count Occurrences
def count_occurrences(lst, elem):
    return deep_flatten(lst).count(elem)

# Average
def average_nested(lst):
    nums = deep_flatten(lst)
    return sum(nums) / len(nums) if nums else 0

print("1. Flatten:", flatten([[1, 2], [3, 4], [5]]))
print("2. Access:", access_nested_element([[1, 2, 3], [4, 5, 6]], [1, 2]))
print("3. Sum:", sum_nested([[1, 2], [3, [4, 5]], 6]))
print("4. Remove:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("5. Max:", find_max([[1, 2], [3, [4, 5]], 6]))
print("6. Count:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("7. Deep Flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print("8. Average:", average_nested([[1, 2], [3, 4], [5, 6]]))

1. Flatten: [1, 2, 3, 4, 5]
2. Access: 6
3. Sum: 21
4. Remove: [[1], [3], [4, 5]]
5. Max: 6
6. Count: 3
7. Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average: 3.5


Numpy

In [ ]:

#initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2,3))
print("A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [ ]:

# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [ ]:
# For a 1-D array:

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim) # Output: 1
# For a 2-D array:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr_2d.ndim) # Output: 2
#For a 3-D array:
arr_3d = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print(arr_3d.ndim) # Output: 3

1
2
3


In [ ]:
print(arr_1d.shape) # Output: (5,)
print(arr_2d.shape) # Output: (2, 3)
print(arr_3d.shape) # Output: (2, 2, 3)

(5,)
(2, 3)
(2, 2, 3)


In [ ]:
print(arr_1d.size) # Output: 5
print(arr_2d.size) # Output: 6
print(arr_3d.size) # Output: 12

5
6
12


In [ ]:
print(arr_1d.dtype) # Output: int64 (or int32)
arr_float = np.array([1.1, 2.2, 3.3])
print(arr_float.dtype) # Output: float64

int64
float64


In [ ]:
print(arr_1d.itemsize) # Output: 8 (for int64)

8


In [ ]:
print(arr_2d.T)
# Output:
# [[1 4]
# [2 5]
# [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
for item in arr_2d.flat:
  print(item, end=" ") # Output: 1 2 3 4 5 6

1 2 3 4 5 6 

In [ ]:
arr_complex = np.array([1+2j, 3+4j])
print(arr_complex.real) # Output: [1. 3.]
print(arr_complex.imag) # Output: [2. 4.]

[1. 3.]
[2. 4.]


In [ ]:
arr_float = arr_2d.astype(float)
print(arr_float)
# Output:
# [[1. 2. 3.]
# [4. 5. 6.]]

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
lst = [[1, 2], [3, 4]]
#print(lst.shape)
# Error: List has no .shape attribute
#Fixing the Error:
arr = np.array(lst)
print(arr.shape) # Output: (2, 2)

(2, 2)


In [ ]:
arr = np.array([1, 2, 3])

# Check if array has more than one dimension
if arr.ndim > 1:
    print(arr.shape[1])
else:
    print("Array is 1D, no second dimension")

Array is 1D, no second dimension


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
#print(arr.shape()) # Error: .shape is an attribute, not a function
print(arr.shape) # Correct usage

(2, 3)


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([1, 2, 3])

try:
    result = a + b
    print(result)
except ValueError as e:
    print(f"Error: {e}")

Error: operands could not be broadcast together with shapes (2,2) (3,) 


In [ ]:
import numpy as np
# Create an array with shape (2, 3)
array = np.array([[1, 2, 3],
[4, 5, 6]])

# Reshape to (3, 2), keeping 6 elements
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)
# Expected Outputs:
# Original Shape: (2, 3)
# Reshaped Shape: (3, 2)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])
#reshaped_array = array.reshape(4, 2)
# Error: cannot reshape array of size 6 into shape (4, 2)

In [ ]:

a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:

# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [ ]:

# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.64560483e-315 0.00000000e+000]
 [6.60379684e-310 6.60378489e-310]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:

array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:

# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) #
Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.13294193e-318 0.00000000e+000 5.78415695e-317]
 [6.60378486e-310 6.60379883e-310 6.60380477e-310]]


In [ ]:

arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [ ]:

# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]]) # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]]) # Shape: (2, 2, 1)
# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (thirddimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)

Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


In [ ]:

# Incorrect shapes
arr1 = np.array([[1, 2], [3, 4]]) # shape (2, 2)
arr2 = np.array([5, 6]) # shape (2,)
# Attempting horizontal stack
try:
  hstacked = np.hstack((arr1, arr2)) # Error due to dimension mismatch
except ValueError as e:
  print(f"Error: {e}")
# Solution: Reshape arr2 to match arr1’s dimensions
arr2 = np.array([5, 6]).reshape(2, 1) # shape (2, 1)
hstacked = np.hstack((arr1, arr2)) # No error
print(hstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[1 2 5]
 [3 4 6]]


In [ ]:

arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]]) # shape (2, 2)
# Attempting horizontal stack (this will fail)
try:
  hstacked = np.hstack((arr1, arr2)) # Error due to shape mismatch
except ValueError as e:
  print(f"Error: {e}")
# Solution: Make sure the number of rows in both arrays is the same before stacking
arr2 = np.array([[7, 8, 9], [10, 11, 12]]) # shape (2, 3)
hstacked = np.hstack((arr1, arr2)) # Works fine
print(hstacked)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:


arr1 = np.array([[1, 2], [3, 4]], dtype=int)
arr2 = np.array([5, 6], dtype=int)

# Convert arr2 to column shape
arr2 = arr2.reshape(2,1)

hstacked = np.hstack((arr1, arr2))
print(hstacked)

[[1 2 5]
 [3 4 6]]


In [ ]:


# Incorrect shapes
arr1 = np.array([[1, 2], [3, 4]])   # shape (2, 2)
arr2 = np.array([5, 6])             # shape (2,)

# Attempting horizontal stack
try:
    hstacked = np.hstack((arr1, arr2))   # Error due to dimension mismatch
except ValueError as e:
    print(f"Error: {e}")

# Solution: Reshape arr2 to match arr1’s dimensions
arr2 = np.array([5, 6]).reshape(2, 1)   # shape (2,1)

hstacked = np.hstack((arr1, arr2))      # No error
print(hstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[1 2 5]
 [3 4 6]]


In [ ]:


arr1 = np.array([[1, 2, 3], [4, 5, 6]])   # shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]])        # shape (2, 2)

# Attempting horizontal stack (this will fail)
try:
    hstacked = np.hstack((arr1, arr2))   # Error due to shape mismatch
except ValueError as e:
    print(f"Error: {e}")

# Solution: Make sure the number of rows in both arrays is the same before stacking
arr2 = np.array([[7, 8, 9], [10, 11, 12]])   # shape (2, 3)

hstacked = np.hstack((arr1, arr2))   # Works fine
print(hstacked)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:


arr1 = np.array([[1, 2], [3, 4]], dtype=int)
arr2 = np.array([5, 6], dtype=float)

# Reshape arr2 to make dimensions compatible
arr2 = arr2.reshape(2,1)

hstacked = np.hstack((arr1, arr2))
print(hstacked)

# Convert datatype to match arr1
arr2 = np.array([5, 6], dtype=int).reshape(2,1)

hstacked = np.hstack((arr1, arr2))
print(hstacked)

[[1. 2. 5.]
 [3. 4. 6.]]
[[1 2 5]
 [3 4 6]]


In [ ]:


arr1 = np.array([[[1, 2], [3, 4]]])   # shape (1, 2, 2)
arr2 = np.array([[5, 6], [7, 8]])     # shape (2, 2)

# Attempting stacking with 3D and 2D arrays
try:
    vstacked = np.vstack((arr1, arr2))   # Error due to different dimensions
except ValueError as e:
    print(f"Error: {e}")

# Solution: Reshape arr1 to be 2D
arr1 = arr1.reshape(2, 2)   # Now shape becomes (2,2)

vstacked = np.vstack((arr1, arr2))   # Works fine
print(vstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:

# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing elements using indexing
print(array[0, 1]) # Output: 2 (first row, second column)
print(array[-1, -1]) # Output: 9 (last row, last column)
# Slicing the array
print(array[0:2, 1:3]) # Output: [[2, 3], [5, 6]]

2
9
[[2 3]
 [5 6]]


In [ ]:

# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
# Attempting to access an element out of bounds
try:
  print(array[2, 1])
except IndexError as e:
  print(f"Error: {e}")

Error: index 2 is out of bounds for axis 0 with size 2


In [ ]:

# Example of basic ufuncs: square and square root
arr = np.array([1, 4, 9, 16])
# Square every element
squared = np.square(arr)
# Square root of every element
sqrt = np.sqrt(arr)
print(f"Squared: {squared}")
print(f"Square root: {sqrt}")

Squared: [  1  16  81 256]
Square root: [1. 2. 3. 4.]


In [ ]:

# Trigonometric ufuncs
angles = np.array([0, np.pi / 4, np.pi / 2])
sine_values = np.sin(angles)
# Logarithmic ufuncs
log_values = np.log(arr)

In [ ]:

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
# Compute determinant
det = np.linalg.det(A)
# Compute inverse
inverse = np.linalg.inv(A)
# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(f"Matrix Product:\n{product}")
print(f"Determinant: {det}")
print(f"Inverse:\n{inverse}")
print(f"Eigenvalues: {eigvals}, Eigenvectors:\n{eigvecs}")

Matrix Product:
[[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132], Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:

A = np.array([[1], [2], [3]]) # Shape (3,1) 3 rows, 1 column
B = np.array([10, 20, 30]) # Shape (3,) 1D array (3 elements)
C = A + B # Works! Result shape: (3,3)
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
A = np.array([[1, 2, 3]]) # Shape (1,3)
B = np.array([[4], [5], [6]]) # Shape (3,1)
C = A + B #Works! Result shape: (3,3)
print(C)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
A = np.ones((3,2)) # Shape (3,2)
B = np.ones((2,3)) # Shape (2,3)
C = A + B #ValueError: operands could not be broadcast together

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [ ]:


A = np.ones((3,2))
B = np.ones((3,2))

C = A + B
print(C)

[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
import numpy as np
import time

# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)

# Using a loop
start_time = time.time()
result_loop = np.zeros(size)

for i in range(size):
    result_loop[i] = a[i] + b[i]

end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")

# Using NumPy vectorized operations
start_time = time.time()

result_vectorized = a + b   # Element-wise addition

end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")

# Performance improvement factor
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 0.48940 seconds
Vectorized Execution Time: 0.00448 seconds
Vectorization is approximately 109.27 times faster!


Numpy Exercise


In [ ]:
#Problem:1
import numpy as np

# Initialize an empty array (2x2)
empty_arr = np.empty((2, 2))
print(" Empty Array (2x2):")
print(empty_arr)

# Initialize an all ones array (4x2)
ones_arr = np.ones((4, 2))
print("\n Ones Array (4x2):")
print(ones_arr)

# New array of given shape filled with a specific value
full_arr = np.full((3, 3), 7)
print("\n Full Array (3x3 filled with 7):")
print(full_arr)
print(f"Shape: {full_arr.shape}, Data Type: {full_arr.dtype}")

# New array of zeros with same shape and type as the full array
zeros_like_arr = np.zeros_like(full_arr)
print("\n Zeros Like Array:")
print(zeros_like_arr)

#  New array of ones with same shape and type as the full array
ones_like_arr = np.ones_like(full_arr)
print("\n Ones Like Array:")
print(ones_like_arr)

# Convert list to NumPy array
new_list = [1, 2, 3, 4]
np_arr = np.array(new_list)
print("\n Array from List:")
print(np_arr)

 Empty Array (2x2):
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

 Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 Full Array (3x3 filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]
Shape: (3, 3), Data Type: int64

 Zeros Like Array:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

 Ones Like Array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

 Array from List:
[1 2 3 4]


In [ ]:
#Problem:2
import numpy as np

#  Create an array with values from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:")
print(arr1)

# Create a 3x3 matrix with values from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n 3x3 Matrix from 0 to 8:")
print(arr2)

# Create a 3x3 identity matrix
identity = np.eye(3)
print("\n 3x3 Identity Matrix:")
print(identity)

# Create a random array of size 30 and find the mean
rand_arr = np.random.random(30)
print("\n Random Array of size 30:")
print(rand_arr)
print("Mean of the array:", rand_arr.mean())

# Create a 10x10 array with random values and find min & max
rand_matrix = np.random.random((10, 10))
print("\n 10x10 Random Array:")
print(rand_matrix)
print("Minimum:", rand_matrix.min(), "Maximum:", rand_matrix.max())

#  Create a zero array of size 10 and replace 5th element with 1
zeros_arr = np.zeros(10)
zeros_arr[4] = 1
print("\n Zero Array with 5th element = 1:")
print(zeros_arr)

# Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n Reversed Array:")
print(reversed_arr)

# Create a 2D array with 1 on border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n 2D Array with 1 on border and 0 inside:")
print(border_arr)

#  Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n 8x8 Checkerboard Pattern:")
print(checkerboard)

Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 3x3 Matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Random Array of size 30:
[0.22077318 0.20932718 0.35581096 0.24543441 0.31352773 0.92112497
 0.65618302 0.86034829 0.58156335 0.83906897 0.26996213 0.24275217
 0.6277816  0.06926939 0.70033895 0.34759623 0.33222554 0.08553405
 0.20899453 0.56852453 0.6651364  0.76943743 0.22805253 0.00348096
 0.77117103 0.04688429 0.74030296 0.04142135 0.82425783 0.04767256]
Mean of the array: 0.4264652840317415

 10x10 Random Array:
[[0.03018935 0.4620763  0.48931921 0.08018865 0.78625583 0.55129932
  0.70830254 0.37904068 0.14469705 0.85532738]
 [0.45852675 0.55945753 0.33346924 0.39452943 0.99295304 0.20819329
  0.63870177 0.59064582 0.59622097 0.87423298]
 [0.05189601 0.03007867 0.30054589 0.12404754 0.41267705 0.74422613
  0.12399995 0.368318

In [ ]:
#Problem 3:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Add the two arrays
print("Addition of x and y:\n", x + y)

#  Subtract the two arrays
print("\nSubtraction of x and y:\n", x - y)

# Multiply array with integer
print("\n x multiplied by 3:\n", x * 3)

# Square of each element
print("\n Square of x elements:\n", x ** 2)

#  Dot products
print("\n Dot Product of v and w:", np.dot(v, w))
print("Dot Product of x and v:", np.dot(x, v))
print("Dot Product of x and y:\n", np.dot(x, y))

# Concatenate
print("\n Concatenate x and y along rows (vstack):\n", np.vstack((x, y)))
print("Concatenate v and w as column (reshape + vstack):\n", np.vstack((v, w)).T)

#  Attempt to concatenate x and v (expecting error)
try:
    np.vstack((x, v))
except ValueError as e:
    print("\n Attempt to concatenate x and v error:\n", e)

Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

 x multiplied by 3:
 [[ 3  6]
 [ 9 15]]

 Square of x elements:
 [[ 1  4]
 [ 9 25]]

 Dot Product of v and w: 219
Dot Product of x and v: [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]

 Concatenate x and y along rows (vstack):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w as column (reshape + vstack):
 [[ 9 11]
 [10 12]]


In [ ]:
#Problem4:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#  Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A^-1 = Identity Matrix:\n", np.dot(A, A_inv))

# Prove AB != BA
print("\n AB:\n", np.dot(A, B))
print("BA:\n", np.dot(B, A))
print("Check AB != BA:", not np.allclose(np.dot(A,B), np.dot(B,A)))

# Prove (AB)^T = B^T A^T
left = np.dot(A, B).T
right = np.dot(B.T, A.T)
print("\n (AB)^T:\n", left)
print("B^T A^T:\n", right)
print("Check equality:", np.allclose(left, right))

#  Solve system of equations using inverse method
# Equations: 2x - 3y + z = -1, x - y + 2z = -3, 3x + y - z = 9
coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
constants = np.array([-1, -3, 9])

solution = np.dot(np.linalg.inv(coeff_matrix), constants)
print("\n Solution of the system (x, y, z):\n", solution)

A * A^-1 = Identity Matrix:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

 AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Check AB != BA: True

 (AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Check equality: True

 Solution of the system (x, y, z):
 [ 2.  1. -2.]


In [ ]:
import time
import numpy as np

# 1. Setup
size = 1_000_000  # 1 million elements
list1 = list(range(size))
list2 = list(range(size))

arr1 = np.arange(size)
arr2 = np.arange(size)


# 2. Element-wise Addition

# Python lists
start = time.time()
res_list_add = [x + y for x, y in zip(list1, list2)]
end = time.time()
print(f"Python List Addition: {end - start:.5f} seconds")

# NumPy arrays
start = time.time()
res_np_add = arr1 + arr2
end = time.time()
print(f"NumPy Array Addition: {end - start:.5f} seconds")

# 3. Element-wise Multiplication

# Python lists
start = time.time()
res_list_mul = [x * y for x, y in zip(list1, list2)]
end = time.time()
print(f"Python List Multiplication: {end - start:.5f} seconds")

# NumPy arrays
start = time.time()
res_np_mul = arr1 * arr2
end = time.time()
print(f"NumPy Array Multiplication: {end - start:.5f} seconds")

# 4. Dot Product

# Python lists
start = time.time()
dot_list = sum(x * y for x, y in zip(list1, list2))
end = time.time()
print(f"Python List Dot Product: {end - start:.5f} seconds")

# NumPy arrays
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print(f"NumPy Array Dot Product: {end - start:.5f} seconds")


# 5. Matrix Multiplication

matrix_size = 300  # smaller to avoid MemoryError in Python lists
# Python lists
list_matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
result_list_matrix = [
    [sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)]
    for row in list_matrix1
]
end = time.time()
print(f"Python List Matrix Multiplication: {end - start:.5f} seconds")

# NumPy arrays
np_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
np_result = np.matmul(np_matrix1, np_matrix2)
end = time.time()
print(f"NumPy Matrix Multiplication: {end - start:.5f} seconds")

Python List Addition: 0.06984 seconds
NumPy Array Addition: 0.00451 seconds
Python List Multiplication: 0.07509 seconds
NumPy Array Multiplication: 0.00933 seconds
Python List Dot Product: 0.08481 seconds
NumPy Array Dot Product: 0.00184 seconds
Python List Matrix Multiplication: 3.40848 seconds
NumPy Matrix Multiplication: 0.02752 seconds
